# Generated by Django 6.0.3 on 2026-04-02 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_address_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='location',
        ),
    ]
