# Generated by Django 6.0.3 on 2026-03-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('request', 'request'), ('waiting', 'waiting'), ('to_airport', 'to_airport'), ('to_hotel', 'to_hotel'), ('dropped_off', 'dropped_off')], default='request', max_length=20)),
            ],
        ),
    ]
