# Generated by Django 6.0.3 on 2026-03-09 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=None, max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999".Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
