# Generated by Django 6.0.3 on 2026-03-10 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_menuitem_customerprofile_driverprofile_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='customer_prpfile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
