# Generated by Django 6.0.3 on 2026-03-10 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='customer_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(unique=True)),
                ('is_default', models.BooleanField()),
                ('adrofuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_s_adress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
