# Generated by Django 6.0.3 on 2026-03-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customerprofile_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
