# Generated by Django 6.0.3 on 2026-04-01 12:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_restrauntmodel_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
