# Generated by Django 6.0.2 on 2026-02-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
